### ISSUE TITLE
Support Custom Port for DNSClient

### ISSUE THREAD

**Issue by akatz0813** [nvivo/ARSoft.Tools.Net#1]
I'd like to request that you support an additional constructor that accepts a custom port for DnsClient.  This is particularly useful when using Consul.io as the local DNS agent listens on port 8600.

public DnsClient(IEnumerable<IPAddress> dnsServers, int queryTimeout, int port)
            : base(dnsServers, queryTimeout, port)
        {
            IsUdpEnabled = true;
            IsTcpEnabled = true;
        }

**Comment by nvivo** [comment]
@akatz0813, this is a mirror repository. I don't do any changes to the code.

Please open your issues on http://arsofttoolsnet.codeplex.com/
